### ISSUE TITLE
postgres backup/restore nicht vollständig

### ISSUE THREAD

**Issue by anrub** [ruslantum/coyo4-backup#4]
In drop_all.sh wird nun das information_schema/pg_catalog nicht gedroppt - d.h. die Tabelle ist vermutlich auch nicht Teil des Backups.
Ist dadurch das Backup nicht unvollständig?

Im Prinzip sollte es möglich sein, eine komplett leere PostgreSQL Datenbank aus dem Restore wieder lauffähig herzustellen.

**Comment by ruslantum** [comment]
https://www.postgresql.org/docs/9.6/static/information-schema.html
https://www.postgresql.org/docs/9.6/static/catalogs.html
die information_schema und pg_catalog Schematas enthalten Postgres interne Meta-Informationen und müssen somit nicht gedroppt und auch nicht gesichert werden.
