### ISSUE TITLE
Reihenfolge restore - Coyo Index Recreate vor dem Restore der Indices richtig?

### ISSUE THREAD

**Issue by anrub** [ruslantum/coyo4-backup#6]
in restore.sh wird erst per curl der recreate der Indices bei Coyo gestartet.
Anschließend werden die ES-Indices per elasticdump neu erstellt.

Müsste der Coyo Index Recreate nicht sequentiell nach dem Restore der ES-Indices stattfinden?

**Comment by ruslantum** [comment]
hier ist die Dokumentation zu den Coyo Manage Api Endpoints:
https://www.coyocloud.com/docs/guide/operations/manage/manage:index#recreate
Recreate erstellt neue Indizies mit den richtigen Mappings, die mit elasticdump nicht gedumpt, und auch nicht wiederhergestellt werden können.
