### ISSUE TITLE
Bitte auch mit der aktuellen 9.0.7-RELEASE testen

### ISSUE THREAD

**Issue by anrub** [ruslantum/coyo4-backup#7]
ob sich im Vergleich zu 7.0.18-RELEASE Änderungen ergeben haben

**Comment by ruslantum** [comment]
bestimmt, aber 9.0.7-RELEASE ist kein offiziell fregegebener Enterprise Release, bitte hier Enterprise Releases folgen:
https://download.coyoapp.com/release/enterprise/
